services:
  - type: web
    name: mosquito-risk-api
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.0"
